version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default_database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
